class Heddle::Course
  include DataMapper::Resource
  storage_names[:heddle] = 'courses'

  property :id,                                     Serial
  property :name,                                   String
  property :account_id,                             Integer
  property :group_weighting_scheme,                 String
  property :old_account_id,                         Integer
  property :workflow_state,                         String
  property :uuid,                                   String
  property :start_at,                               DateTime
  property :conclude_at,                            DateTime
  property :grading_standard_id,                    Integer
  property :is_public,                              Integer
  property :allow_student_wiki_edits,               Integer
  property :created_at,                             DateTime
  property :updated_at,                             DateTime
  property :show_public_conText_messages,           Integer
  property :syllabus_body,                          Text
  property :allow_student_forum_attachments,        Integer
  property :default_wiki_editing_roles,             String
  property :wiki_id,                                Integer
  property :allow_student_organized_groups,         Integer
  property :course_code,                            String
  property :default_view,                           String
  property :abstract_course_id,                     Integer
  property :root_account_id,                        Integer
  property :enrollment_term_id,                     Integer
  property :sis_source_id,                          String
  property :sis_batch_id,                           Integer
  property :show_all_discussion_entries,            Integer
  property :open_enrollment,                        Integer
  property :storage_quota,                          Integer
  property :tab_configuration,                      Text
  property :allow_wiki_comments,                    Integer
  property :turnitin_comments,                      Text
  property :self_enrollment,                        Integer
  property :license,                                String
  property :indexed,                                Integer
  property :restrict_enrollments_to_course_dates,   Integer
  property :template_course_id,                     Integer
  property :locale,                                 String
  property :settings,                               Text
  property :replacement_course_id,                  Integer
  property :stuck_sis_fields,                       Text
  property :public_description,                     Text
  property :self_enrollment_code,                   String
  property :self_enrollment_limit,                  Integer
end
